### ISSUE TITLE
Make sure we can link to route starting now

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/hyperRail#107]
Feature request through twitter:

https://twitter.com/Robin61/status/595234777432793089

**Comment by nicoverbruggen** [comment]
This was actually in, but it redirected. Seems to be broken now. Also, noticed that debug is on on the live server ;)

e.g. https://irail.be/route/Antwerpen/Mechelen should be bookmarkable and will always redirect to the proper page. (But it's broken right now)
