### ISSUE TITLE
Vagrant throwing some problems. 

### ISSUE THREAD

**Issue by Tjoosten** [iRail/hyperRail#119]
Hi, I use a mac OSX (yosimite). 

and i get the following error:

```bash 
 The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
hostnamectl set-hostname 'irail'
Stdout from the command:
Stderr from the command:
stdin: is not a tty
bash: line 2: hostnamectl: command not found
```

@pietercolpaert note: @brechtvdv  do you have time to bump the vagrant to Ubuntu 14.04

**Comment by pietercolpaert** [comment]
Or maybe @bramdevries?

**Comment by bramdevries** [comment]
The old vagrant setup still works for me (OS X 10.10), at which point is it giving that error @Tjoosten ?

**Comment by bramdevries** [comment]
Turns out someone at work had the same issue with Vagrant and it was a bug in vagrant `1.7.3`, upgrading to `1.7.4` should fix it.

**Comment by Tjoosten** [comment]
Alright i will try that out tonight.

**Comment by Tjoosten** [comment]
Fixed
