### ISSUE TITLE
Slide open animation on results page is not smooth

### ISSUE THREAD

**Issue by nicoverbruggen** [iRail/hyperRail#12]
When on mobile, the animation when toggling open entries on the results page after planning a route, is not smooth. Since this is a basic Bootstrap element, not sure if we can fix this without rewriting the entire animation.

**Comment by pietercolpaert** [comment]
And? ;-) @nicoverbruggen

**Comment by nicoverbruggen** [comment]
I'd refrain from changing this. To get smooth animations you'd have to rewrite a lot or go native, and we already have nice solutions on mobile like Railer on iOS.

**Comment by pietercolpaert** [comment]
Feel free to close then :)
