### ISSUE TITLE
API interprets Kapellen (Antwerp) station as Capellen - Kapellen(L) station

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/hyperRail#122]
Hello,

I have just been reported this bug by user email. 
I have issues with Kapellen (Antwerp - https://en.wikipedia.org/wiki/Kapellen,_Belgium) that is mixed with Chapelle-Capellen (German version = Kapellen) in Luxembourg (https://en.wikipedia.org/wiki/Capellen) 

http://api.irail.be/connections/?to=bergen&from=kapellen

Next version of BeTrains will use station ID everywhere, but currently, I cannot do anything on my side, unfortunately.

Can something be done on the server for this?

**Comment by pietercolpaert** [comment]
This is an annoying bug as well in our autocomplete list... You can only select Kapellen in Luxenburg at this moment.

Also over here it's missinterpreted: http://api.irail.be/vehicle/?id=L2591

I propose this issue to be fixed as follows:

An optional parameter `&fromCountry` and `&toCountry` will be implemented to make sure we know what country we're talking about

**Comment by pietercolpaert** [comment]
Seems like in fact kapellen is always with a K and Capellen (l) is always with a C now. Will fix in stations list
