### ISSUE TITLE
Braine L'Alleud (and maybe other) not working since the fixes.

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/hyperRail#129]
Hello all,

As I sent by email, it seems that all the previous fixes introduced a new bug.
From the feedback I received, this bug appeared in "the previous weeks": 

EDIT: all Bruxelles stations are also broken (Brussels is OK)!

http://api.irail.be/connections.php?to=MONS&from=BRAINE%20L%27ALLEUD

Full request: 
http://api.irail.be/connections.php?to=MONS&from=BRAINE%20L%27ALLEUD&date=190815&time=0656&timeSel=depart&lang=en&typeOfTransport=train&format=json&fast=true

Thank a lot.

Edit: using the '-' instead of the space to match https://github.com/iRail/stations/blob/master/stations.csv doesn't give better result

**Comment by pietercolpaert** [comment]
Thank you for this issue @ChristopheVersieux. This has now been fixed. Together with this issue, I also found out things like http://api.irail.be/vehicle.php/?id=4529 didn't work, which do now.
