### ISSUE TITLE
Improvement ideas. 

### ISSUE THREAD

**Issue by Tjoosten** [iRail/hyperRail#139]
I started this discussion because i'm wondering on some points. 

## Ideas on versioning. 

- Use [semver](http://semver.org) for versioning. 

#### Make a changelog for every version.
I was thinking to make a locked issue that holds al the changes in this format: `<checkbox> <issue idea> <issue title>`

## Ideas to improve contributing experience. 
- Add a contributing file. 
- Make labels for the bug tracker i was thinking of the following labels:
  - `Low priority` 
  - `Medium priority`
  - `High priority`
  - `Confirmed` 
  - `Duplicate`
  - `Feature`
  - `Version <version number>`

**Comment by pietercolpaert** [comment]
We want to make the barrier to contribute as low as possible... So not every contributor should be aware of the details in my opinion. It's good that we apply this ourselves after an issue was made though!

**Comment by Tjoosten** [comment]
And another idea what if we make a bot for managing issues and that kind of stuff like Bootstrap does?

**Comment by Tjoosten** [comment]
@pietercolpaert I like to add contribution file. So the user has the choice to read the file or not.

**Comment by pietercolpaert** [comment]
We'll keep it as is for now. The project has too little funding to have a higher barrier contribution guide.
