### ISSUE TITLE
Error 502 for "la louviere centre"

### ISSUE THREAD

**Issue by ChristopheVersieux** [iRail/hyperRail#144]
It is currently impossible to get any result for search including "La louvière centre".
According to the user, the issue appeared "a few days ago", so it looks like this was working before the changes.

Example URL: http://api.irail.be/connections.php?to=OBOURG&from=LA%20LOUVIERE%20CENTRE&date=240815&time=1407&timeSel=depart&lang=en&typeOfTransport=train&format=json&fast=true

Thank a lot.

**Comment by Tjoosten** [comment]
I think this is more a api issue then a hyperRail issue. Correct me if i wrong!

**Comment by ChristopheVersieux** [comment]
You are right, I wasn't sure where to put all the issues.
Will now use iRail for everything

**Comment by Tjoosten** [comment]
Hmm maybe it is better to put the report in the repo of the API.

**Comment by pietercolpaert** [comment]
https://irail.be/route?to=http%3A%2F%2Firail.be%2Fstations%2FNMBS%2F008881000&from=http%3A%2F%2Firail.be%2Fstations%2FNMBS%2F008882107&date=240815&time=1527&timeSel=depart works now. Can you double check?
