### ISSUE TITLE
Improve docblocks.

### ISSUE THREAD

**Issue by Tjoosten** [iRail/hyperRail#148]
Hi, 

i was thinking. Maybe it is a good idea to improve the docblocks that are used in this application. 

Now: 

```php 
/**
*  <short description>
 * @param <variable>
 * @return <type>
 */
```
And i want to convert it to something like this. 

```php 
/**
 * <short description of the functions>
 *
 * @param <type> <variable> <short description>
 * @return <type>
 */
```

everyone agreed with me? if not i like to hear your feedback.

**Comment by brechtvdv** [comment]
I dont' think explaining different functions together is a good idea

**Comment by Tjoosten** [comment]
Hmm. I my opinion it is better then just only document the params.

**Comment by pietercolpaert** [comment]
I don't want to overdocument the docblocks in this repository. I agree that it would be better, but it will raise the bar for future students that contribute to the project. Something I want to avoid.
