### ISSUE TITLE
Set german translations. 

### ISSUE THREAD

**Issue by Tjoosten** [iRail/hyperRail#151]

**Comment by pietercolpaert** [comment]
Won't fix

**Comment by xavez** [comment]
@pietercolpaert should we remove the german translation file from the source code to clean it up?

**Comment by Tjoosten** [comment]
I have something local if we want the german translation files. I just can push them.

**Comment by xavez** [comment]
@Tjoosten can you explain what you mean or make a PR? I’m not sure what "something" means :)

**Comment by Tjoosten** [comment]
I updated the keys in the german translation files.
