### ISSUE TITLE
StyleCI integration

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/hyperRail#154]
I feel like we shouldn't be too strict here, while styleci by default is really strict. Can we trim down the configuration of styleci to be more forgiving?

**Comment by SaschaDens** [comment]
It's possible to configure styleCi to use presets. One of the supported presets is [Laravel](https://styleci.readme.io/docs/presets#laravel).

It's not that StyleCi is too strict, you just don't want diffrent coding styles in the project. This will increase the complexity for the developer. Using StyleCi will make it possible to spot diffrences quickly and it's an easy check if the pull requests from contributors match your styleguide.
