### ISSUE TITLE
Calendar monday to sunday

### ISSUE THREAD

**Issue by mclaeysb** [iRail/hyperRail#169]
The current calendar is Sunday to Saturday. Calendars in Belgium are Monday to Sunday. 
When looking up a train, it's easy to assume "ah, saturday, it's the forlast in the row" and click there, without looking at the names of the weekdays on top.

It's a small thing, but it will avoid wrong results and sad users.

**Comment by mclaeysb** [comment]
Front-end is quite new to me, but I think I just found out how it should be done. Give me 24h to try and make my first pull request ;-)

**Comment by brechtvdv** [comment]
:+1:

**Comment by pietercolpaert** [comment]
Cool! Looking forward @mclaeysb!

**Comment by mclaeysb** [comment]
Finally had some more time to look at it, but I can't seem to get it running on localhost. Can I get some more info on which type of localhost server I should set up, and how that should be done?

**Comment by pietercolpaert** [comment]
@mclaeysb an apache + PHP server should work fine. Did you try out the set-up process as described in the README.md? Can you pinpoint where you got stuck?

**Comment by mclaeysb** [comment]
Made some progress already :) , but I'm getting an error. What I did so far:
- Setting up an Apache server using MAMP, from the hyperrail directory, with PHP 7.
- Went through all Readme.md steps successfully (except optional update bootstrap) (although I must note that I had to `composer install` before I could `composer update`, which is not mentioned in the Readme.md).
- Accessed `http://localhost:8888/public/index.php`, with the page loading without styling, and the following error on top of the screen.

![screen shot 2016-05-03 at 18 25 19](https://cloud.githubusercontent.com/assets/2920134/14990368/8ca6ab3a-115c-11e6-9708-fc9c04f5f210.png)

Did I have to update bootstrap? If so, how (there's no bootstrap/start.php file).

Thanks!

**Comment by mclaeysb** [comment]
Anyone who can help me in the meantime?

**Comment by Tjoosten** [comment]
@mclaeysb in what point of view u need help?

**Comment by pietercolpaert** [comment]
@Tjoosten See #171 → for some reason the installation is not fully working. Can you try the installation instructions and get it to work?

**Comment by Tjoosten** [comment]
For some reason i can't reproduce this error?? :s

**Comment by mclaeysb** [comment]
Installation issues, ah, always so personal :)

It would be helpful if I knew if whether I have to update or install or do something else with 'bootstap' during the installation. Or if you think you can identify what other thing went wrong causing my [error](https://github.com/iRail/hyperRail/issues/169#issuecomment-216586398). Thanks!

**Comment by mclaeysb** [comment]
Thanks!
