### ISSUE TITLE
Update readme & check installation instructions

### ISSUE THREAD

**Issue by nicoverbruggen** [iRail/hyperRail#171]
I quickly tried to see if I could reproduce #169 in 5 mins with a clean zip from the repo and by following the instructions. 

Personally, I'm having trouble even getting installing dependencies using npm install. (I am running a fairly new version of npm, which has caused me some grief on other projects as well -- but that's besides the point). 

I think we should take a look at the readme and required packages and see if they cannot be upgraded so that it's easier to set up.

**Comment by pietercolpaert** [comment]
@nicoverbruggen This is now fixed!

**Comment by pietercolpaert** [comment]
And a duplicate of #180 ;)
