### ISSUE TITLE
Why are there two Sass source folders?

### ISSUE THREAD

**Issue by xavez** [iRail/hyperRail#186]
Why is there a `sass` folder here: https://github.com/iRail/hyperRail/tree/master/resources/assets/sass and here: https://github.com/iRail/hyperRail/tree/master/public/app/sass ?

**Comment by xavez** [comment]
Related: the `sass` folder in `public` seems to be the one used by the grunt task, shouldn’t it be the one in the `resources` folder?

**Comment by Tjoosten** [comment]
Relates: #180 
Your right. I will try to fix this when i resolve #180.

**Comment by xavez** [comment]
Fixed when #190 is merged
