### ISSUE TITLE
Why are rendered CSS files committed in the repository?

### ISSUE THREAD

**Issue by xavez** [iRail/hyperRail#187]
I’m trying to do a simple fix and . . . nothing but questions! ;).

Why are the rendered `CSS` files committed in the repository? I’m talking about this one: https://github.com/iRail/hyperRail/tree/master/public/app/css

**Comment by Tjoosten** [comment]
Relates: #180 
Your right. I will try to fix this when i resolve #180.

**Comment by Tjoosten** [comment]
Good question. I also don't know. @pietercolpaert can maybe provide a answer.

**Comment by pietercolpaert** [comment]
@nicoverbruggen did this a couple of years ago as a first angularjs project. I guess things can be a lot better overall.

Feel free to apply the boyscout rule here and leave the code/documentation more clean than it was. Today, the putting it in production process was however pretty simple: only a git pull was needed.

**Comment by xavez** [comment]
So the answer is: because there is no deploy process? Fine for me, I am not the right person to implement post-get deploy hooks. Closing :-)
