### ISSUE TITLE
Show platform number on every result header

### ISSUE THREAD

**Issue by xavez** [iRail/hyperRail#196]
I think we should show the platform number of the first train in every result block header.

The danger is that this could become quite cluttered when we add the spitsgids icons.

Is there a new design for showing the free/busy information? Don’t want to undo someone else’s work 😄.

**Comment by pietercolpaert** [comment]
@serkanyildiz has made some mock-ups of this:
![slides for metro - 2016-07-22](https://cloud.githubusercontent.com/assets/347073/17077197/7a9ce3e6-50c7-11e6-8473-94afe3247287.png)

**Comment by xavez** [comment]
Ok, so no HTML/CSS code was written yet?

**Comment by pietercolpaert** [comment]
@serkanyildiz did write HTML/CSS already. I cannot find it online anywhere though...
