### ISSUE TITLE
Console error when opening route form

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/hyperRail#201]
```
Error: [$parse:syntax] Syntax Error: Token 'results' is an unexpected token at column 10 of the expression [planning results] starting at [results]
```

Happens when opening first page of iRail.be. @xavez any idea?

**Comment by SerkanYildiz** [comment]
Have this error too, but It's gone when you replace
`<div class="routeplanner view1" ng-show="planning results">`
with
`<div class="routeplanner view1" ng-show="results">`
in file resources/views/_partials/route/planner.blade.php.  But I don't know if it will break something else or not.

**Comment by xavez** [comment]
@SerkanYildiz you should probably merge `upstream/master` into your branch, error is fixed :-)

**Comment by xavez** [comment]
(I also think this issue can be closed @pietercolpaert?)

**Comment by pietercolpaert** [comment]
Indeed! Thanks for fix!

**Comment by SerkanYildiz** [comment]
Yep saw your fix! Thanks
