### ISSUE TITLE
Public directory from sass files.

### ISSUE THREAD

**Issue by Tjoosten** [iRail/hyperRail#213]
<img width="1009" alt="schermafbeelding 2016-07-28 om 11 14 40" src="https://cloud.githubusercontent.com/assets/5157609/17207430/dbbcfc60-54b4-11e6-9c9b-6c0ca92e4561.png">

**Comment by pietercolpaert** [comment]
Is that a problem? You'll only get it when you're playing with the URL, and maybe when you're playing with the URL you want to see what's in our public folders, which I think everyone should be able to do?

**Comment by Tjoosten** [comment]
in my opinion it's a bad practice. Because i'm used to don't show these files.

**Comment by pietercolpaert** [comment]
We chose to show them!

Please do give a more elaborate description next time of your problem. What may be a bad practice in one project may not be a bad practice in the other.
