### ISSUE TITLE
The copyright year in the footer is 2015

### ISSUE THREAD

**Issue by SerkanYildiz** [iRail/hyperRail#216]
The copyright year in the footer is 2015. Isn't it better to take the current year in the template? I would love to fix this.

**Comment by xavez** [comment]
I believe the copyright notice should also say "Copyright ©" in full, since the "©" symbol by itself bears no legal meaning.

**Comment by pietercolpaert** [comment]
Putting a copyright notice under a page is useless anyway: websites are © by default, so in fact we could just get rid of it as well

**Comment by SerkanYildiz** [comment]
Okay, so we remove the copyright text from the footer?

**Comment by pietercolpaert** [comment]
It's okay. You can leave it as is for now :)

Op zo 31 jul. 2016 20:11 schreef Serkan Yildiz <notifications@github.com>:
