### ISSUE TITLE
Feedback form is shown on the wrong moment

### ISSUE THREAD

**Issue by SerkanYildiz** [iRail/hyperRail#217]
![bug-feedback](https://cloud.githubusercontent.com/assets/299328/17218917/b6023a1e-54e9-11e6-8ad7-5912e59ae71f.png)
Time I took this screenshot is 17:30. As you can see, sometimes the feedback is not shown, while it has to be. 

I'm going to fix this. I will take the time the train leaves.

**Comment by Haroenv** [comment]
I think the feedback should be shown for the whole ride time of that train (in this case 19:57-20:13)

**Comment by SerkanYildiz** [comment]
Don't agree with that @Haroenv . We should show it before it departs and a while when it arrives.

**Comment by Haroenv** [comment]
Yep, a margin added to that seems useful

**Comment by xavez** [comment]
- We should be able to get the departure data from the iRail api somehow, no? What the maximum delta is between arrival and departure of a train? In my experience, 5 minutes can even be short sometimes :).
- As for the margin after you were on a train, I would say half an hour or so should be safe?
