### ISSUE TITLE
Links in iOS "save to homescreen" mode open in browser

### ISSUE THREAD

**Issue by Haroenv** [iRail/hyperRail#221]
For some reason this is the default behaviour, but can be "solved" by setting the `window.location` via JS on click on an `a`. However we should (if we do this) only do this on iOS, since it's kind of a hack.

source: https://stackoverflow.com/questions/2898740/iphone-safari-web-app-opens-links-in-new-window

**Comment by xavez** [comment]
Yep, that’s a known iOS issue.

I’m not sure whether we should implement the hack: it’s extra lines of code (and we’re trying to get rid of them) plus I think with Railer there is a very good alternative on your phone?

If we really want to make a web app you can pin to your home screen, it’s probably a better idea to Switch to a technology like React and use React's routing (as in JS, not trains). That would take a while though :-).

**Comment by Haroenv** [comment]
Yep. I just put it here since it's an issue I noticed. It could be fixed but doesn't necessarily. It makes sense not to fix this

**Comment by pietercolpaert** [comment]
Not sure about whether we should fix this either as I don't have an i-device. I guess I can close this as the general direction is wont-fix?

**Comment by xavez** [comment]
👍
