### ISSUE TITLE
Reason why the build fails in TravisCI

### ISSUE THREAD

**Issue by SerkanYildiz** [iRail/hyperRail#225]
I found the reason why TravisCI is failing everytime. 
It's just because that we don't run the command php artisan key:generate after the install. This sould be fixed.

**Comment by Haroenv** [comment]
tried this in #226, but it didn't work.

**Comment by SerkanYildiz** [comment]
Logs?

**Comment by Haroenv** [comment]
https://travis-ci.org/iRail/hyperRail/builds/152163793 

* https://travis-ci.org/iRail/hyperRail/jobs/152163794
* https://travis-ci.org/iRail/hyperRail/jobs/152163795
* https://travis-ci.org/iRail/hyperRail/jobs/152163796
* https://travis-ci.org/iRail/hyperRail/jobs/152163797

**Comment by SerkanYildiz** [comment]
Maybe you can fix it with this: [Laravel & Travis CI](https://github.com/orchestral/testbench#no-supported-encrypter-found-the-cipher-and--or-key-length-are-invalid)

**Comment by Haroenv** [comment]
Should be fixed in #227 (currently still running, but I get 1 checkmark already by combining these two things)

**Comment by SerkanYildiz** [comment]
Nice :) Good job

2016-08-14 22:34 GMT+02:00 Haroen Viaene <notifications@github.com>:

**Comment by SerkanYildiz** [comment]
I think this issue can be marked as solved @pietercolpaert @Haroenv
