### ISSUE TITLE
Occupancy feedback dropdown icons are blurry

### ISSUE THREAD

**Issue by Haroenv** [iRail/hyperRail#229]
Probably just a question of using the svg versions there too, and not small png versions.

**Comment by SerkanYildiz** [comment]
Will ask Arne if he haves SVG versions of the icons.

**Comment by SerkanYildiz** [comment]
No SVG available, but there are .AI files. Can you convert them to SVG? Check on drive.google.com in our project directory

**Comment by Haroenv** [comment]
Yep, that's possible
