### ISSUE TITLE
Use of unsafe html templating

### ISSUE THREAD

**Issue by Haroenv** [iRail/hyperRail#248]
There are both laravel (blade) (`{{}}`) and angular bangs (`@{{}}`), there isn't any need for `{!! !!}`, which is laravel unsafe substitution. The language strings don't contain any html, so they can be changed without any other refactoring needed

see https://github.com/iRail/hyperRail/pull/246#issuecomment-257250399

**Comment by Tjoosten** [comment]
Can i assign me to this one?
