### ISSUE TITLE
Looking up a journey advice only works on the second try

### ISSUE THREAD

**Issue by hemmofa** [iRail/hyperRail#255]
When I go to iRail.be, and enter a station in both From and To fields and then press 'plan route', almost always my first try gives no result. When I click 'plan route' again, it does work.

My browser does a request as seen in element inspector / network log, and it even gets a result which seems to be identical to the one on the second try.

I have no further details, but it seems to be easily reproducible.

**Comment by Haroenv** [comment]
You're right, I haven't seen this happen before, but now I have it too, no errors being logged though. 

Maybe #253 already fixes this?

**Comment by pietercolpaert** [comment]
Something to do with server configuration... Ticket is opened with our hosting provider

**Comment by pietercolpaert** [comment]
Fixed by now! Forgot to close this issue
