### ISSUE TITLE
HHVM build failed: HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.

### ISSUE THREAD

**Issue by kidk** [iRail/hyperRail#259]
It seems the TravisCI cannot build the current master branch because of a dependency on HHVM. Can we remove the dependency or add `dist: trusty` to the .travis.yml file?

**Comment by Bertware** [comment]
HHVM, PHP5.5 and PHP5.6 are removed from testing, PHP7.1 was added instead.
