### ISSUE TITLE
Implement a vehicle endpoint

### ISSUE THREAD

**Issue by Bertware** [iRail/hyperRail#271]
Implement an endpoint for the vehicle ids used in the irail api. This will prevent 404 errors when someone follows the link.

**Comment by Bertware** [comment]
Current implmentation
![screen shot 2017-10-26 at 17 11 38-fullpage](https://user-images.githubusercontent.com/1094793/32061020-cda3d162-ba70-11e7-8a5c-c9ca96ef46fa.png)

**Comment by pietercolpaert** [comment]
Looks cool!
