### ISSUE TITLE
Class 'Locale' not found

### ISSUE THREAD

**Issue by Ditger** [iRail/hyperRail#285]
I made the db but it is still empty? 
I did do the npm install,  bower install, but when I do grunt it gives a not found error, 
also when I do php artisan serve I get this error:Class 'Locale' not found

I'm new to laravel but I would love to learn it so I hope someone can help me out with setting it up

EDIT; I did install compass so when I do grunt it just gives a bunch of errors but my server starts like before so still the error and in the console 404 errors that it can't find the build/something.css like 12 times or something

**Comment by Bertware** [comment]
Do you have the php_intl module installed?

**Comment by Ditger** [comment]
https://imgur.com/a/VxfaN

these are the photos after I used brew install php70-intl

**Comment by Bertware** [comment]
Please make sure the intl module is loaded, usually it's installed using apt-get or yum on Linux, I'm not familiar with installing it any other way, and given the fact that the error is stilling popping up, I'd say it's not installed or enabled properly. 

Running bower or anything shouldn't be necessary unless you modify the javascript or css, built files should be included in the repository already.

Here are a few pointers which might help you out
https://secure.php.net/manual/en/class.locale.php
https://stackoverflow.com/questions/18346531/how-to-enable-php-locale-class

**Comment by Ditger** [comment]
It is fixed, I used this now: brew install homebrew/php/php70-intl instead of this: brew install php70-intl

And I thought I needed one but it works now
