### ISSUE TITLE
Problem with CORS

### ISSUE THREAD

**Issue by ClumsyPenguin** [iRail/hyperRail#290]
All the api GET request stating me and error about Cross orgin resource sharing 
Please fix this

**Comment by Bertware** [comment]
Hi,
In order to resolve any possible issues, we need more information

- Which URL are you trying to retrieve?
- What are you aiming to do (so we may assist you in case there are better endpoints available)

**Comment by ClumsyPenguin** [comment]
A GET from https://data.irail.be/NMBS/Stations
And thr liveboard

**Comment by Bertware** [comment]
You are not supposed to retrieve information from data.irail.be (it's an old system for one specific partner for legacy reasons).

Please use [api.irail.be](https://api.irail.be). Documentation can be found at [docs.irail.be](https://docs.irail.be). The correct github repository for this is https://github.com/iRail/iRail

**Comment by Bertware** [comment]
https://api.irail.be/stations/ works fine here - please pay attention to the documentation

**Comment by ClumsyPenguin** [comment]
![screenshot from 2018-05-25 15-32-24](https://user-images.githubusercontent.com/22469147/40546935-dd31fbe8-6030-11e8-87e0-f12a83c41cd2.png)
![screenshot from 2018-05-25 15-32-13](https://user-images.githubusercontent.com/22469147/40546946-e0cdde66-6030-11e8-9e7e-da3db9204f72.png)
i just use these code and it gives ma an empty 200 error this is client based i know , my postman does work in angular it won't do you know a solution

**Comment by Bertware** [comment]
As described in the documentation, available at https://docs.irail.be , you can use the format parameter: https://api.irail.be/stations/?format=json
