### ISSUE TITLE
Testing & monitoring

### ISSUE THREAD

**Issue by Tuinslak** [iRail/hyperRail#36]
If we want to move iRail from the garage to something professional, where commercial parties (such as @FlatTurtle) rely on, we need to introduce a QoS. 

From my understanding, data.iRail.be will be sunset in a couple of months (what about api.irail.be ?). 

It would be good to provide a dashboard with daily (or hourly) results for ALL data on iRail.be (not just NMBS, but also TEC, MIVB, De Lijn, etc).
Ideally, the (failed) tests results should be broadcast using e-mail, twitter, etc. Perhaps a health status API could be handy as well ?

Todo:

* [ ] document ALL the code, APIs, etc. Make it newb-friendly (push for universities to use our data for freshmen exercises)
* [ ] fix #31 
* [ ] create an automatic testing interface, that tests http results, checks for correct date & output, etc
* [x] create a status dashboard with historic data
* [ ] get automated results in your inbox (& twitter feed)

Examples:
* http://devel.datif.be/irail/test.html (http://devel.datif.be/2010/12/03/using-continuous-integration-testing-to-test-the-irail-api-backend/)
* http://devel.datif.be/jquery.irail/

**Comment by pietercolpaert** [comment]
*  Travis ci is implemented for the testing interface. We need better tests though
 * dashboard with historic data: moved this to https://github.com/iRail/analytics → http://analytics.irail.be (status: experimental)
 * Documentation is becoming better, and it's becoming easier to set up as we go

I hope we get an intern next year which can work further on the issues listed here :)

**Comment by pietercolpaert** [comment]
This is more a roadmap than a simple to fix issue. This will be fixed however in the future by using analytics.irail.be. Summer of code 2016 will introduce an archiving framework which should be able to show how good our information was/is overall.

Will close this issue for now
