### ISSUE TITLE
Display canceled  trains

### ISSUE THREAD

**Issue by pietercolpaert** [iRail/hyperRail#37]
When delay is "cancel" it should also be shown in the GUI

**Comment by jncn** [comment]
Any news on this?

**Comment by pietercolpaert** [comment]
Fixed in https://github.com/iRail/hyperRail/commit/63729f5906534f1cc4bdbbf99a153fb70c2a8e54 and https://github.com/iRail/hyperRail/commit/0358816c09affc24175c76594c205d81b4b0fe76
