### ISSUE TITLE
mismatch between railtime info and iRail

### ISSUE THREAD

**Issue by oliverw1** [iRail/hyperRail#93]
For several years now, I've been running a small website that keeps track of the delays users encounter when going to (and from) work on a daily basis. It's been working extremely well. It's similar to belate.be, with that exception that this app can process cross-overs ("overstap" in English?) between stations and does a few more things automatically for the end-users. I've been keeping it low-profile, because history teaches us that the NMBS likes to threaten juridically projects like these, as iRail no doubt knows. ;-) 

Recently I've been looking into the iRail API again, to get the source data from, but I find that it deviates sometimes from the data published by infrabel. As an example (time limited due to infrabel's website), check out [train 3639 from Landen to De Panne on 2015-01-05](http://www.railtime.be/mobile/HTML/TrainDetail.aspx?l=NL&s=2&ret=SearchTrain&tid=3639&dt=05%2F01%2F2015&dep=Zoeken). Compare this to the third option in the [list of possible routes between Aalst and Gent-Sint-Pieters from that same timestamp](https://irail.be/route?to=http%3A%2F%2Firail.be%2Fstations%2FNMBS%2F008892007&from=http%3A%2F%2Firail.be%2Fstations%2FNMBS%2F008895000&date=050115&time=1641&timeSel=depart).
If needed, I'll try to find another example that is valid for another week.

Anyway: why is this data different? I don't know enough about the iRail code to know where it gets its source data from, even though I've been keeping the iRail project in my mind since the beginning of this app.

Edit: is it because I'm misunderstanding the iRail representation of data? That it doesn't take retardations into account?

**Comment by nicoverbruggen** [comment]
Apologies for the late comment, I haven't been keeping up with the developments here for a while. I believe that this issue might be relevant for the scraper repository. (This repository is mostly front-end stuff and does some data conversions, experiments into hypermedia API etc.) 

You can find the scraper repo here: https://github.com/iRail/iRail

**Comment by oliverw1** [comment]
Thanks for the redirect. I've opened the issue over there as [number 39](https://github.com/iRail/iRail/issues/39). Feel free to close this one.
